swagger: "2.0"

info:
  version: "1.1.0-impl:etsi.org:ETSI_NFV_OpenAPI:1"
  title: "SOL011 - NS Fault Management Interface"
  description: >
    SOL011 - NS Fault Management Interface
    IMPORTANT: Please note that this file might be not aligned to the current
    version of the ETSI Group Specification it refers to and has not been
    approved by the ETSI NFV ISG. In case of discrepancies the published ETSI
    Group Specification takes precedence.
    Please report bugs to https://forge.etsi.org/rep/nfv/SOL011/-/issues
  license:
    name: "ETSI Forge copyright notice"
    url: https://forge.etsi.org/etsi-forge-copyright-notice.txt
  contact:
    name: "NFV-SOL WG"

externalDocs:
  description: ETSI GS NFV-SOL 011 V4.4.1
  url: https://www.etsi.org/deliver/etsi_gs/NFV-SOL/001_099/011/04.04.01_60/gs_NFV-SOL011v040401p.pdf

basePath: /nsfm/v1

schemes:
  - http
  - https

consumes:
  - application/json

produces:
  - application/json

paths:
  "/api_versions":
    $ref: 'https://forge.etsi.org/rep/nfv/SOL005/-/raw/2.6.1-maintenance/src/SOL005/NSFaultManagement/NSFaultManagement.yaml#/paths/~1api_versions'
  "/alarms":
    $ref: 'https://forge.etsi.org/rep/nfv/SOL005/-/raw/2.6.1-maintenance/src/SOL005/NSFaultManagement/NSFaultManagement.yaml#/paths/~1alarms'
  "/alarms/{alarmId}":
    $ref: 'https://forge.etsi.org/rep/nfv/SOL005/-/raw/2.6.1-maintenance/src/SOL005/NSFaultManagement/NSFaultManagement.yaml#/paths/~1alarms~1{alarmId}'
  "/subscriptions":
    $ref: 'https://forge.etsi.org/rep/nfv/SOL005/-/raw/2.6.1-maintenance/src/SOL005/NSFaultManagement/NSFaultManagement.yaml#/paths/~1subscriptions'
  "/subscriptions/{subscriptionId}":
    $ref: 'https://forge.etsi.org/rep/nfv/SOL005/-/raw/2.6.1-maintenance/src/SOL005/NSFaultManagement/NSFaultManagement.yaml#/paths/~1subscriptions~1{subscriptionId}'