swagger: "2.0"

info:
  version: "1.1.0-impl:etsi.org:ETSI_NFV_OpenAPI:1"
  title: "SOL011 - NSD Management Interface"
  description: >
    SOL011 - NSD  Management Interface
    IMPORTANT: Please note that this file might be not aligned to the current
    version of the ETSI Group Specification it refers to and has not been
    approved by the ETSI NFV ISG. In case of discrepancies the published ETSI
    Group Specification takes precedence.
    Please report bugs to https://forge.etsi.org/bugzilla/buglist.cgi?component=Nfv-Openapis
  license:
    name: "ETSI Forge copyright notice"
    url: https://forge.etsi.org/etsi-forge-copyright-notice.txt
  contact:
    name: "NFV-SOL WG"

externalDocs:
  description: ETSI GS NFV-SOL 011 V3.7.1
  url: https://www.etsi.org/deliver/etsi_gs/NFV-SOL/001_099/011/03.07.01_60/gs_NFV-SOL011v030701p.pdf

basePath: /nsd/v1

schemes:
  - http
  - https

consumes:
  - application/json

produces:
  - application/json

paths:
  "/api_versions":
    $ref: 'https://forge.etsi.org/rep/nfv/SOL005/-/raw/v2.6.1/src/SOL005/NSLifecycleManagement/NSLifecycleManagement.yaml#/paths/~1api-versions'

  "/ns_descriptors":
    parameters:
      - name: Authorization
        description: >
          The authorization token for the request.
          Reference: IETF RFC 7235.
        in: header
        required: false
        type: string
      - name: Version
        description: >
          Version of the API requested to use when responding to this request.
        in: header
        required: true
        type: string
    get:
      $ref: 'https://forge.etsi.org/rep/nfv/SOL005/-/raw/v2.6.1/src/SOL005/NSDManagement/NSDManagement.yaml#/paths/~1ns_descriptors/get'

  '/ns_descriptors/{nsdInfoId}':
    parameters:
      - name: nsdInfoId
        description: >
          Identifier of the individual NS descriptor resource.
        in: path
        required: true
        type: string
      - name: Authorization
        description: >
          The authorization token for the request.
          Reference: IETF RFC 7235.
        in: header
        required: false
        type: string
      - name: Version
        description: >
          Version of the API requested to use when responding to this request.
        in: header
        required: true
        type: string
    get:
      $ref: 'https://forge.etsi.org/rep/nfv/SOL005/-/raw/v2.6.1/src/SOL005/NSDManagement/NSDManagement.yaml#/paths/~1ns_descriptors~1{nsdInfoId}/get'

