swagger: "2.0"

info:
  version: "1.2.0-impl:etsi.org:ETSI_NFV_OpenAPI:1"
  title: "SOL011 - NS Lifecycle Management Interface"
  description: >
    SOL011 - NS Lifecycle Management Interface
    IMPORTANT: Please note that this file might be not aligned to the current
    version of the ETSI Group Specification it refers to and has not been
    approved by the ETSI NFV ISG. In case of discrepancies the published ETSI
    Group Specification takes precedence.
    Please report bugs to https://forge.etsi.org/bugzilla/buglist.cgi?component=Nfv-Openapis
  license:
    name: "ETSI Forge copyright notice"
    url: https://forge.etsi.org/etsi-forge-copyright-notice.txt
  contact:
    name: "NFV-SOL WG"

externalDocs:
  description: ETSI GS NFV-SOL 011 V3.7.1
  url: https://www.etsi.org/deliver/etsi_gs/NFV-SOL/001_099/011/03.07.01_60/gs_NFV-SOL011v030701p.pdf


basePath: /callback/v1

schemes:
  - http
  - https

consumes:
  - application/json
produces:
  - application/json

paths:
  '/URI_is_provided_by_the_client_when_creating_the_subscription-NsLcmOperationOccurrenceNotification':
    $ref: 'https://forge.etsi.org/rep/nfv/SOL005/-/raw/2.6.1-maintenance/src/SOL005/NSLifecycleManagementNotification/NSLifecycleManagementNotification.yaml#/paths/~1URI_is_provided_by_the_client_when_creating_the_subscription-NsLcmOperationOccurrenceNotification'
  '/URI_is_provided_by_the_client_when_creating_the_subscription-NsIdentifierCreationNotification':
    $ref: 'https://forge.etsi.org/rep/nfv/SOL005/-/raw/2.6.1-maintenance/src/SOL005/NSLifecycleManagementNotification/NSLifecycleManagementNotification.yaml#/paths/~1URI_is_provided_by_the_client_when_creating_the_subscription-NsIdentifierCreationNotification'
  '/URI_is_provided_by_the_client_when_creating_the_subscription-NsIdentifierDeletionNotification':
    $ref: 'https://forge.etsi.org/rep/nfv/SOL005/-/raw/2.6.1-maintenance/src/SOL005/NSLifecycleManagementNotification/NSLifecycleManagementNotification.yaml#/paths/~1URI_is_provided_by_the_client_when_creating_the_subscription-NsIdentifierDeletionNotification'